### ISSUE TITLE
Need karma not mocha

### ISSUE THREAD

**Issue by cPTheme** [cPhost/dom-manager#7]
## Please specify the issue

- [X] Bug
- [ ] Feature Request

##### Define Issue Below 

Well looks like mocha ci testing is not working we need karma
even sauce labs no idea what to do with it.

**Comment by cPhost** [comment]
Well karma seems to be failing to!!

**Comment by cPhost** [comment]
But anyways we will be able to do just need perfect config 
Sauce Labs seems to lock me out for running it on CI? Wierd
